CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_member FOREIGN KEY (member_id) REFERENCES members(id)
);

CREATE TABLE coaching_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    coach_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN,
    CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_coach FOREIGN KEY (coach_id) REFERENCES coaches(id)
);

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    member_id BIGINT NOT NULL,
    check_in_time TIMESTAMP,
    CONSTRAINT fk_member_attendance FOREIGN KEY (member_id) REFERENCES members(id)
);

